baseURL = 'https://stamotenti.it/'
title = 'StamoTenti'

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

[taxonomies]
tag = 'tags'
author = 'authors'
source = 'sources'
sottoarea = 'sotto_area'
tema = 'temi'

[languages]

[languages.it]
label = 'Italiano'
locale = 'it-IT'
weight = 1

[languages.en]
label = 'English'
locale = 'en-US'
weight = 2
